### ISSUE TITLE
Ticker API, Help with Development

### ISSUE THREAD

**Issue by djalmaaraujo** [thiagopinheirolima/brokerage-notes-parser#3]
Hello @thiagopinheirolima. I am also building this parser with a calculator. I already have an API with tickers and other useful information.

Do you have plans to make this system more robust or you are just doing this for personal usage?

**Comment by thiagopinheirolima** [comment]
Hello @djalmaaraujo, I do have plans to improve this system. Do you know if this ticker api uses the same name showed on brokerage notes or do we need to parse before use it?
